### ISSUE TITLE
Nothing here.

### ISSUE THREAD

**Issue by x0xDJSx0x** [spongeyperson/OpenCoreEFI-G513QY#1]
I don't see anything on my screen.

**Comment by spongeyperson** [comment]
Working on it. This repository is currently a placeholder until i obtain files used in the process of installing MacOS to the ROG G15 Advantage (G513QY) Laptop.

**Comment by spongeyperson** [comment]
Solved in PR #3, Project now has contents. Thank you x0xDJSx0x
